// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddInItem struct {
	Name     string  `json:"name"`
	AddedPpu float64 `json:"addedPPU"`
}

type AddInItemInput struct {
	Name     string  `json:"name"`
	AddedPpu float64 `json:"addedPPU"`
	Quantity int     `json:"quantity"`
}

type CreamerOption struct {
	Name     string  `json:"name"`
	AddedPpu float64 `json:"addedPPU"`
}

type CreamerOptionInput struct {
	Name     string  `json:"name"`
	AddedPpu float64 `json:"addedPPU"`
	Quantity int     `json:"quantity"`
}

type DrinkItem struct {
	Name           string           `json:"name"`
	ProductID      string           `json:"productID"`
	Price          float64          `json:"price"`
	Currency       string           `json:"currency"`
	Description    string           `json:"description"`
	SizeOptions    []*string        `json:"sizeOptions"`
	CreamerOptions []*CreamerOption `json:"creamerOptions"`
	AddOn          []*AddInItem     `json:"addOn"`
}

type DrinkOrder struct {
	Name           string                `json:"name"`
	ProductID      string                `json:"productID"`
	SizeOption     string                `json:"sizeOption"`
	CreamerOptions []*CreamerOptionInput `json:"creamerOptions"`
	AddOn          []*AddInItemInput     `json:"addOn"`
}

type FoodItem struct {
	Name        string  `json:"name"`
	ProductID   string  `json:"productID"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Currency    string  `json:"currency"`
}

type FoodOrder struct {
	Name      string `json:"name"`
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
	Notes     string `json:"notes"`
}

type Menu struct {
	LocationName    string       `json:"locationName"`
	LocationAddress string       `json:"locationAddress"`
	DrinkItems      []*DrinkItem `json:"drinkItems"`
	FoodItems       []*FoodItem  `json:"foodItems"`
}

type NewOrder struct {
	CustomerName     string        `json:"customerName"`
	DrinksOrdered    []*DrinkOrder `json:"drinksOrdered"`
	FoodItemsOrdered []*FoodOrder  `json:"foodItemsOrdered"`
	Price            float64       `json:"price"`
}

type Order struct {
	OrderNum         string       `json:"orderNum"`
	CustomerName     string       `json:"customerName"`
	DrinksOrdered    []*DrinkItem `json:"drinksOrdered"`
	FoodItemsOrdered []*FoodItem  `json:"foodItemsOrdered"`
	Price            float64      `json:"price"`
	Success          bool         `json:"success"`
}
